Repository dentproject/testing, pull requests merged in 2023-04, with the labels that each got.

#208 Add ability to delete traffic item by name
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tgen_utils.py
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
Labels: automerge

#237 github action for pre-commitcheck and auto comment on PR
  .github/workflows/pre-commit-check.yml
Labels: automerge

#234 Pr pre commit
  docs/Code_commit_process/README.md
Labels: automerge

#203 Add vlan tests
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_default_configuration.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_switching_modes.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_tagged_ports.py
Labels: automerge, phase1

#212 Add increment mac vlan test
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_increment_mac.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/data/platforms.json
Labels: automerge, phase1

#186 Update run tests howto and docker environment
  .github/configs/.wordlist.txt
  DentOS_Framework/Dockerfile
  DentOS_Framework/Dockerfile.testing
  DentOS_Framework/run.sh
  docs/How_to_start_and_run_testcases.md
Labels: documentation, enhancement, phase1

#238 Add devlink_port API
  DentOS_Framework/DentOsTestbedLib/gen/model/dent/network/devlink/devlink.yaml
  DentOS_Framework/DentOsTestbedLib/gen/model/linux/network/devlink/devlink.yaml
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/devlink/__init__.py
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/devlink/devlink_port.py
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/devlink/linux/__init__.py
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/devlink/linux/devlink_port.py
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/devlink/linux/devlink_port_impl.py
  DentOS_Framework/DentOsTestbedLib/test/test_dent_devlink_port.py
Labels: automerge

#223 Update bridge_link_impl, bridge_mdb_impl, ip_link_impl
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/bridge/linux/linux_bridge_link_impl.py
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/bridge/linux/linux_bridge_mdb_impl.py
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ip/linux/linux_ip_link_impl.py
Labels: automerge

#240 Add IPv6 basic config and bridge tests
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/__init__.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/conftest.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/ipv6_utils.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_bridge.py
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
Labels: automerge

#210 Add L1 traffic tests
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_autodetect.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_autoneg.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_forced_speed.py
Labels: automerge, phase1

#307 Update function param, add wait to tests
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_autodetect.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_default_configuration.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_increment_mac.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_priority.py
Labels: phase1

#305 Add IPv6/IPv4 and IPv6 route tests
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/conftest.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/ipv6_utils.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_bridge.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_ipv4.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_route.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/cleanup_utils.py
Labels: phase2

#311 Fix parse_show method in Ethtool API
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ethtool/linux/linux_ethtool_impl.py
Labels: phase1

#296 F841 local variable 'parse_cmd_body' is assigned to but never used
  .pre-commit-config.yaml
  DentOS_Framework/DentOsTestbedLib/gen/plugins/test/plugin.py
Labels: bug

#314 Fix ethtool show for link partner mode
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ethtool/linux/linux_ethtool_impl.py
Labels: automerge
