Repository dentproject/testing, pull requests merged in 2023-03, with the labels that each got.

#74 Add support for petunia and tc tests
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/tc/__init__.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/tc/flower/__init__.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/tc/flower/test_tc_flower_persistency.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/tc/flower/test_tc_flower_persistency_atomic_update.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tc_flower_utils.py
Labels: enhancement

#206 QUAGGA_CONFIG update
  DentOS_Framework/DentOsTestbed/configuration/testbed_config/sit/agg1/QUAGGA_CONFIG
  DentOS_Framework/DentOsTestbed/configuration/testbed_config/sit/agg2/QUAGGA_CONFIG
  DentOS_Framework/DentOsTestbed/configuration/testbed_config/sit/dist1/QUAGGA_CONFIG
  DentOS_Framework/DentOsTestbed/configuration/testbed_config/sit/infra1/QUAGGA_CONFIG
  DentOS_Framework/DentOsTestbed/configuration/testbed_config/sit/infra2/QUAGGA_CONFIG
Labels: bug, automerge

#175 Add ACL tests
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/acl/__init__.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/acl/test_acl.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/acl/test_acl_all_selectors.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/acl/test_acl_negative.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tc_flower_utils.py
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/tc/linux/linux_tc_filter_impl.py
Labels: automerge

#187 Fix vlan pvid set
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/bridge/linux/linux_bridge_vlan_impl.py
Labels: automerge

#188 Add frame rate support
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
Labels: automerge

#191 Fix parse_multivalue
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
Labels: automerge

#181 Add packet TTL option
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
Labels: automerge

#184 Add recoverable sysctl and cleanup function
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/conftest.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/cleanup_utils.py
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/os/linux/linux_sysctl_impl.py
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/os/recoverable_sysctl.py
Labels: automerge

#200 Add IPv6 support
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tgen_utils.py
  DentOS_Framework/DentOsTestbedLib/gen/model/dent/traffic/traffic.yaml
  DentOS_Framework/DentOsTestbedLib/gen/model/traffic/ixia/ixia.yaml
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client.py
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/traffic_gen.py
Labels: enhancement, automerge

#213 Ethernet card support
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
Labels: automerge

#214 Add QoS tests
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/qos/__init__.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/qos/conftest.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/qos/constants.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/qos/test_qos_class_precedence.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/qos/test_qos_default_prio.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/qos/test_qos_dscp_remarking.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/qos/test_qos_shaper.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/qos/test_qos_trust_mode.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/cleanup_utils.py
Labels: automerge

#217 Add L1 configuration tests(no traffic)
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_config.py
Labels: automerge

#218 Add mixed speed test
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_mixed_speed.py
Labels: automerge

#209 remove empty file
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/dentv2/switching/test_vlan_port_isolation_nat.py
Labels: automerge

#221 set auto instrumentation mode
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
Labels: automerge

#224 Added ability to change transmission control mode
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
Labels: automerge

#230 Fix ACL Scale tests
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/dentv2/acl/scale/test_acl_scale_max_rules.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/dentv2/acl/scale/test_acl_scale_max_rules_store.py
Labels: automerge

#193 Add bum traffic tests
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/bridging_packet_types.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_port.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_forward_block_different_packets.py
Labels: automerge

#231 Add Igmp traffic and totalLength
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
Labels: automerge

#232 add second port to each device to ixia tester
  DentOS_Framework/DentOsTestbed/configuration/testbed_config/sit/agg1/NETWORK_INTERFACES
  DentOS_Framework/DentOsTestbed/configuration/testbed_config/sit/agg2/NETWORK_INTERFACES
  DentOS_Framework/DentOsTestbed/configuration/testbed_config/sit/dist1/NETWORK_INTERFACES
  DentOS_Framework/DentOsTestbed/configuration/testbed_config/sit/infra1/NETWORK_INTERFACES
  DentOS_Framework/DentOsTestbed/configuration/testbed_config/sit/infra2/NETWORK_INTERFACES
  DentOS_Framework/DentOsTestbed/configuration/testbed_config/sit/testbed.json
Labels: automerge
