Repository dentproject/testing, pull requests merged in 2023-06, with the labels that each got.

#340 Regression fixes
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/conftest.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_autodetect.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_autoneg.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_config.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_forced_speed.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_mixed_speed.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_port_state.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/acl/test_acl_all_selectors.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_admin_state_down_up.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_ageing.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_port.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_forwarding.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_jumbo_frame.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_static_entries.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_unreg_traffic_ipv6.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/devlink/test_devlink_interact.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/devlink/test_devlink_sct.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/devlink/test_devlink_shared_block.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/devlink/test_devlink_single_block.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_arp.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_best_match.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_en_dis_fwd.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_gw.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv4/test_ipv4_routing.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_nei.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/policer/test_policer_dynamic_traps.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/policer/test_policer_interaction_with_span.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/policer/test_policer_rate_per_rule.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_basic_functionality.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_incremental_mac_addresses.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_interaction_ports_inside_lag.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_interaction_route_between_vlan_devices.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_interaction_vlan_membership.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/storm_control_utils.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/test_storm_control_rule_set_for_br_and_mc_traffic.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/test_storm_control_rule_set_for_br_and_unk_uc_traffic.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/storm_control/test_storm_negative_known_unicast_traffic.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_increment_mac.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tc_flower_utils.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tgen_utils.py
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/tc/linux/linux_tc_filter_impl.py
Labels: phase2

#341 Add IPv6 ICMP test
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_route.py
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
Labels: automerge, phase2

#351 Add stp support to ip link api
  DentOS_Framework/DentOsTestbedLib/gen/model/dent/network/ip/link.yaml
  DentOS_Framework/DentOsTestbedLib/gen/model/linux/network/ip/link.yaml
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ip/linux/linux_ip_link_impl.py
Labels: automerge, phase3

#350 Add mstpctl API
  DentOS_Framework/DentOsTestbedLib/gen/model/dent/network/mstpctl/mstpctl.yaml
  DentOS_Framework/DentOsTestbedLib/gen/model/linux/network/mstpctl/mstpctl.yaml
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/mstpctl/__init__.py
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/mstpctl/linux/__init__.py
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/mstpctl/linux/linux_mstpctl.py
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/mstpctl/linux/linux_mstpctl_impl.py
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/mstpctl/mstpctl.py
  DentOS_Framework/DentOsTestbedLib/test/test_dent_mstpctl.py
Labels: automerge, phase3

#342 Restore VLAN test (tagged_packet_size)
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_tagged_size.py
Labels: automerge, phase2

#347 Test table size tests
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_jumbo_frame.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_mac_table_size.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/table_size/__init__.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/table_size/test_table_size.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/data/platforms.json
Labels: automerge, phase3

#344 Add port_isolation_vlan_interfaces test
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_interaction_route_between_vlan_devices.py
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_vlan_interfaces.py
Labels: automerge, phase2

#349 Add lag support to ixia
  DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tgen_utils.py
  DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/traffic/ixnetwork/ixnetwork_ixia_client_impl.py
Labels: automerge, phase3
